### ISSUE TITLE
proposed modification on KerasGA

### ISSUE THREAD

**Issue by tfarrag2000** [ahmedfgad/KerasGA#1]
Dear Dr. Ahmed,
I try to use your wonderful library to train some models and it works great. but I notice errors with certain models. I solve these errors by concentrate on training the "trainable weights" only. 
My modification is as follow:

![image](https://user-images.githubusercontent.com/25705994/103832943-ad6c4a00-5090-11eb-98de-dcdd97f819db.png)

**Comment by ahmedfgad** [comment]
Dear Prof. Tamer,

I will fix it soon!

Thanks too much!

**Comment by tfarrag2000** [comment]
Thank you, Dr. Ahmed

**Comment by ahmedfgad** [comment]
The change is reflected and will be pushed soon to the new release of PyGAD 2.10.1. Thanks.
